### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ci70** [shrpnsld/amalgamate#1]
Doesn't seem to work.

`c:\jemalloc-dev\src>bash amalgamate.sh -e "c,cpp" -H`

```
FIND: Parameter format not correct
FIND: Parameter format not correct
amalgamate error: no C/C++ files found
```

UPDATE: Ah I see. Seems like it was using the Windows version of Find.

Can you add a switch to ignore if it cannot find a header? Would be useful for system headers etc.

**Comment by shrpnsld** [comment]
Hello, @optomux :) Sorry for not responding.

Can you specify your environment and maybe provide some test sample of your source tree structure, so I can trace the issue? Though, if your `bash` uses Windows version of `find`, I don't think I can do much about that. 

> Would be useful for system headers etc.

It already ignores system headers, because there's no real reason in expanding them.

> `c:\jemalloc-dev\src>bash amalgamate.sh -e "c,cpp" -H`

Also I see, that you are specifying source extensions using the header extension option `-e`. In your case you should use the `-s` option. But I don't think you really need to specify extensions, because by default, amalgamate searches for files with all the C/C++ header and source extensions, which are:
"h", "hh", "hpp", "hxx", "h++", "tpp", "txx", "tpl", "ii", "ixx", "ipp", "inl" and "c", "cc", "cpp", "cxx", "c++".
